on: pull_request
name: Run Impacted Tests
jobs:
  test-job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Find changed files
      run: |
        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
        echo "::set-output name=files::$FILES"
      id: changed_files
    
    - name: Run impacted tests
      run: |
        for file in steps.changed_files.outputs.files
        do
          filename="$(basename -- $file)"
          extension="${filename##*.}"
          if [ ${extension} == "py" ]
          then
            parentdir="$(basename "$(dirname "$file")")"
            echo ${parentdir}
            name="${filename%.*}"
            test_file_name=${parentdir}/${name}_test.py
            echo ${test_file_name}
          fi
        done
 
   
